version: "3.6"

services:
     web:
       build: .
       container_name: portal
       command: python3 manage.py runserver 127.0.0.1:8000
       volumes:
        - .:/portal
       ports:
        - "8000:8000"
       depends_on:
        - db
     db:
       image: mongo:4.0
